### ISSUE TITLE
More native-style English on Haskell Aliases article

### ISSUE THREAD

**Issue by tomjaguarpaw** [vrom911/vrom911.github.io#51]
Hi Veronika,

Thanks for a great article on Haskell aliases! I think it's really important to share knowledge like this because unlike source code this knowledge is not generally written down in repositories.

I was wondering if you would like me to submit a PR with suggestions to make the English more like a native speaker would write it. I would be happy to do so.

https://github.com/vrom911/vrom911.github.io/blob/develop/blog/2020-09-25-haskell-aliases.md

**Comment by vrom911** [comment]
Thank you 😊 
Yes, of course! I would really appreciate that! As you notice, I am not a native speaker, so any suggestions are valuable 🙏🏼
